<?php
	require_once("$webRoot/etc/include.php");
	require_once("$webRoot/lib/include/include.php");
	require_once("$webRoot/lib/ortak/include.php");
	require_once("$webRoot/classes/cIO/include.php");
	require_once("$webRoot/classes/ortak/include.php");
	require_once("$webRoot/lib/session/include.php");
	require_once("$webRoot/lib/config/include.php");
	require_once("$webRoot/lib/layoutBase/include.php");
	require_once("$webRoot/lib/partBase/include.php");
	require_once("$webRoot/lib/appBase/include.php")
?>
