CREATE TABLE IF NOT EXISTS yflaglar (
	kod TEXT NOT NULL PRIMARY KEY,
	tanim TEXT NOT NULL DEFAULT '',
	jsonstr TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS isyeri (
	kod TEXT NOT NULL PRIMARY KEY,
	aciklama TEXT NOT NULL DEFAULT '',
	silindi TEXT NOT NULL DEFAULT ''
);
INSERT OR IGNORE INTO isyeri (kod) VALUES ('');

CREATE TABLE IF NOT EXISTS stkanagrup (
	kod TEXT NOT NULL PRIMARY KEY,
	aciklama TEXT NOT NULL DEFAULT ''
);
INSERT OR IGNORE INTO stkanagrup (kod) VALUES ('');

CREATE TABLE IF NOT EXISTS stkgrup (
	kod TEXT NOT NULL PRIMARY KEY,
	aciklama TEXT NOT NULL DEFAULT '',
	anagrupkod TEXT NOT NULL DEFAULT ''
);
INSERT OR IGNORE INTO stkgrup (kod) VALUES ('');

CREATE TABLE IF NOT EXISTS stokmarka (
	kod TEXT NOT NULL PRIMARY KEY,
	aciklama TEXT NOT NULL DEFAULT ''
);
INSERT OR IGNORE INTO stokmarka (kod) VALUES ('');

CREATE TABLE IF NOT EXISTS stkmst (
	kod TEXT NOT NULL PRIMARY KEY,
	aciklama TEXT NOT NULL DEFAULT '',
	silindi TEXT NOT NULL DEFAULT '',
	calismadurumu TEXT NOT NULL DEFAULT '*',
	satilamazfl TEXT NOT NULL DEFAULT '',
	oscolor INTEGER,
	brm TEXT NOT NULL DEFAULT '',
	brm2 TEXT NOT NULL DEFAULT '',
	brmorani REAL NOT NULL DEFAULT 0,
	grupkod TEXT NOT NULL DEFAULT '',
	smarkakod TEXT NOT NULL DEFAULT '',
	kisaadi TEXT NOT NULL DEFAULT '',
	satkdvorani INTEGER NOT NULL DEFAULT 0,
	almkdvorani INTEGER NOT NULL DEFAULT 0,
	rbkbedenkategorikod TEXT NOT NULL DEFAULT '',
	tartilabilir TEXT NOT NULL DEFAULT '',
	tartireferans NOT NULL DEFAULT '',
	satfiyat1 REAL NOT NULL DEFAULT 0,
	satfiyat2 REAL NOT NULL DEFAULT 0,
	satfiyat3 REAL NOT NULL DEFAULT 0,
	satfiyat4 REAL NOT NULL DEFAULT 0,
	satfiyat5 REAL NOT NULL DEFAULT 0,
	satfiyat6 REAL NOT NULL DEFAULT 0,
	satfiyat7 REAL NOT NULL DEFAULT 0,
	satfiyat8 REAL NOT NULL DEFAULT 0,
	satfiyat9 REAL NOT NULL DEFAULT 0,
	almfiyat REAL NOT NULL DEFAULT 0
);
INSERT OR IGNORE INTO stkmst (kod) VALUES ('');

CREATE TABLE IF NOT EXISTS stkmemo (
	stokkod TEXT NOT NULL,
	memo TEXT NOT NULL DEFAULT '',
	PRIMARY KEY (stokkod, memo)
)
