
CREATE TABLE IF NOT EXISTS yflaglar (
	kod TEXT NOT NULL PRIMARY KEY,
	tanim TEXT NOT NULL DEFAULT '',
	jsonstr TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS isyeri (
	kod TEXT NOT NULL PRIMARY KEY,
	aciklama TEXT NOT NULL DEFAULT '',
	silindi TEXT NOT NULL DEFAULT ''
);
INSERT OR IGNORE INTO isyeri (kod) VALUES ('');
