<?php require_once("$webRoot_ticari/classes/ortak/hmr/include-ilk.php"); $_partRoot = "$webRoot_ticari/classes/mq-master" ?>
<script src="<?=$_partRoot?>/mqEMail.js?<?=$appVersion?>"></script>
<script src="<?=$_partRoot?>/mqSube.js?<?=$appVersion?>"></script>
<script src="<?=$_partRoot?>/mqIsyeri.js?<?=$appVersion?>"></script>
<script src="<?=$_partRoot?>/mqDoviz.js?<?=$appVersion?>"></script>
<script src="<?=$_partRoot?>/mqStokIslem.js?<?=$appVersion?>"></script>
<script src="<?=$_partRoot?>/mqUretimIslem.js?<?=$appVersion?>"></script>
<script src="<?=$_partRoot?>/mqStokYer.js?<?=$appVersion?>"></script>
<script src="<?=$_partRoot?>/mqYerRaf.js?<?=$appVersion?>"></script>
<script src="<?=$_partRoot?>/mqStokDepartman.js?<?=$appVersion?>"></script>
<script src="<?=$_partRoot?>/mqVergiGrup.js?<?=$appVersion?>"></script>
<script src="<?=$_partRoot?>/mqVergi.js?<?=$appVersion?>"></script>
<script src="<?=$_partRoot?>/mqMuhHesap.js?<?=$appVersion?>"></script>
<script src="<?=$_partRoot?>/mqGTip.js?<?=$appVersion?>"></script>
<script src="<?=$_partRoot?>/mqStokMensei.js?<?=$appVersion?>"></script>
<script src="<?=$_partRoot?>/mqBarkodReferans.js?<?=$appVersion?>"></script>
<script src="<?=$_partRoot?>/mqYukGrup.js?<?=$appVersion?>"></script>
<script src="<?=$_partRoot?>/mqStokAnaGrup.js?<?=$appVersion?>"></script>
<script src="<?=$_partRoot?>/mqStokGrup.js?<?=$appVersion?>"></script>
<script src="<?=$_partRoot?>/mqStokIstGrup.js?<?=$appVersion?>"></script>
<script src="<?=$_partRoot?>/mqStok.js?<?=$appVersion?>"></script>
<script src="<?=$_partRoot?>/mqKategori.js?<?=$appVersion?>"></script>
<script src="<?=$_partRoot?>/mqHizmetGrup.js?<?=$appVersion?>"></script>
<script src="<?=$_partRoot?>/mqHizmetIstGrup.js?<?=$appVersion?>"></script>
<script src="<?=$_partRoot?>/mqHizmet.js?<?=$appVersion?>"></script>
<script src="<?=$_partRoot?>/mqDemirbas.js?<?=$appVersion?>"></script>
<script src="<?=$_partRoot?>/mqSatisTipi.js?<?=$appVersion?>"></script>
<script src="<?=$_partRoot?>/mqSatisRota.js?<?=$appVersion?>"></script>
<script src="<?=$_partRoot?>/mqUlke.js?<?=$appVersion?>"></script>
<script src="<?=$_partRoot?>/mqEIslOzelYontem.js?<?=$appVersion?>"></script>
<script src="<?=$_partRoot?>/mqEIslemOzelDip.js?<?=$appVersion?>"></script>
<script src="<?=$_partRoot?>/mqCariIl.js?<?=$appVersion?>"></script>
<script src="<?=$_partRoot?>/mqCariAnaBolge.js?<?=$appVersion?>"></script>
<script src="<?=$_partRoot?>/mqCariBolge.js?<?=$appVersion?>"></script>
<script src="<?=$_partRoot?>/mqCariTip.js?<?=$appVersion?>"></script>
<script src="<?=$_partRoot?>/mqCariIstGrup.js?<?=$appVersion?>"></script>
<script src="<?=$_partRoot?>/mqCari.js?<?=$appVersion?>"></script>
<script src="<?=$_partRoot?>/mqPlasiyer.js?<?=$appVersion?>"></script>
<script src="<?=$_partRoot?>/mqSevkAdres.js?<?=$appVersion?>"></script>
<script src="<?=$_partRoot?>/mqAltHesapGrup.js?<?=$appVersion?>"></script>
<script src="<?=$_partRoot?>/mqAltHesap.js?<?=$appVersion?>"></script>
<script src="<?=$_partRoot?>/mqKasa.js?<?=$appVersion?>"></script>
<script src="<?=$_partRoot?>/mqBanka.js?<?=$appVersion?>"></script>
<script src="<?=$_partRoot?>/mqBankaHesap.js?<?=$appVersion?>"></script>
<script src="<?=$_partRoot?>/mqBankaSube.js?<?=$appVersion?>"></script>
<script src="<?=$_partRoot?>/mqPosKrediHesapOrtak.js?<?=$appVersion?>"></script>
<script src="<?=$_partRoot?>/mqTahsilSekli.js?<?=$appVersion?>"></script>
<script src="<?=$_partRoot?>/mqTakipNo.js?<?=$appVersion?>"></script>
<script src="<?=$_partRoot?>/mqPortjoy.js?<?=$appVersion?>"></script>
<script src="<?=$_partRoot?>/mqStokCariRef.js?<?=$appVersion?>"></script>
<script src="<?=$_partRoot?>/mqEConf.js?<?=$appVersion?>"></script>
<?php require_once("$webRoot_ticari/classes/ortak/hmr/include-son.php")?>
